// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANld1vys97Mqc4HgX8ewM58XcwG12ZBrU',
    appId: '1:579233536043:web:14d7f874932444d9dab26e',
    messagingSenderId: '579233536043',
    projectId: 'whatapp-clone-e5a9d',
    authDomain: 'whatapp-clone-e5a9d.firebaseapp.com',
    storageBucket: 'whatapp-clone-e5a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGYtfcWLa5hryHUA6RPO0AxXDOWT3KP_w',
    appId: '1:579233536043:android:1b7e1e66ca24e40adab26e',
    messagingSenderId: '579233536043',
    projectId: 'whatapp-clone-e5a9d',
    storageBucket: 'whatapp-clone-e5a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGuHJSApoqczDyQpM1wW_ic3vheNWKUQ',
    appId: '1:579233536043:ios:9dd6c84edf61ad7bdab26e',
    messagingSenderId: '579233536043',
    projectId: 'whatapp-clone-e5a9d',
    storageBucket: 'whatapp-clone-e5a9d.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
